### ISSUE TITLE
System.IO.FileLoadException

### ISSUE THREAD

**Issue by ckelsoe** [christianhelle/sqlcequery#1]
Hi,

When I open a SDF file I immediately get the following error:

```
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Temp\SQL Compact Query Analyzer 1.0.2.25483\SqlCe40\SqlCeDatabase40.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Temp\SQL Compact Query Analyzer 1.0.2.25483\SqlCe40\SqlCeDatabase40.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at ChristianHelle.DatabaseTools.SqlCe.SqlCeDatabaseFactory.LoadSqlCe40()
   at ChristianHelle.DatabaseTools.SqlCe.SqlCeDatabaseFactory.GetImplementation(SupportedVersions version)
   at ChristianHelle.DatabaseTools.SqlCe.SqlCeDatabaseFactory.GetImplementation(String connectionString)
   at ChristianHelle.DatabaseTools.SqlCe.SqlCeDatabaseFactory.Create(String connectionString)
   at ChristianHelle.DatabaseTools.SqlCe.QueryAnalyzer.ViewModel.MainViewModel.<AnalyzeDatabase>b__2()
```

`
I have confirmed that the SqlCeDatabase40.dll file it is looking for are in the C:\Temp\SQL Compact Query Analyzer 1.0.2.25483\SqlCe40\ folder. 

How can that be corrected?

**Comment by christianhelle** [comment]
That's first time I heard of this

Can you provide some version info on the machine your running? Like Windows and .NET version?

**Comment by martindelisle** [comment]
I ran into the same issue. I'm running Windows 10 (10.0.16299.371) and have .Net Frmk 4.6.1.

**Comment by christianhelle** [comment]
Oh! That’s a bit bad, SqlCeDatabase40.dll is a library provided by Microsoft and I didn’t expect them to block that. Thanks for this @martindelisle. I might have a few ideas for a fix

**Comment by christianhelle** [comment]
Thanks for this @martindelisle. I might have a few ideas for a proper fix.

**Comment by christianhelle** [comment]
The correct fix for this would be to add these lines to app.config

```
   <runtime>  
      <loadFromRemoteSources enabled="true"/>  
   </runtime> 
```

I'll rebuild the setup packages and fix the portable package later

**Comment by martindelisle** [comment]
Thank you!
